
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

#logging:
#  level:
#    root: debug