ALTER TABLE rooms ADD COLUMN created_by BIGSERIAL;
ALTER TABLE rooms ADD COLUMN updated_by BIGSERIAL;
ALTER TABLE rooms ADD COLUMN created_at TIMESTAMP;
ALTER TABLE rooms ADD COLUMN updated_at TIMESTAMP;